AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an ECR repository."

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AWS::StackName}
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  ECRRepositoryURI:
    Description: "The URI of the ECR repository."
    Value: !Sub "${MyECRRepository.RepositoryUri}"
